version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
    labels:
      - dependencies
      - github-actions
    open-pull-requests-limit: 10
    groups:
      github-actions-all:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    labels:
      - dependencies
      - submodule
    groups:
      gitsubmodule-all:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: scope
    labels:
      - dependencies
      - python
    ignore:
      - dependency-name: pip
    open-pull-requests-limit: 10
    groups:
      pip-all:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: scope
    labels:
      - dependencies
      - python
    ignore:
      - dependency-name: pip
    open-pull-requests-limit: 10
    groups:
      uv-all:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: "chore"
      include: scope
    labels:
      - dependencies
      - javascript
    open-pull-requests-limit: 10
    groups:
      npm-all:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: "chore"
      include: scope
    labels:
      - dependencies
      - javascript
    open-pull-requests-limit: 10
    groups:
      bun-all:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: scope
    labels:
      - dependencies
      - rust
    open-pull-requests-limit: 10
    groups:
      cargo-all:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: rust-toolchain
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    labels:
      - dependencies
      - rust
    groups:
      rust-toolchain-all:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: "docker"
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    groups:
      docker-all:
        patterns: ["*"]
        update-types: [minor, patch]
