title = "gitleaks config"

[allowlist]
  description = "ignore false positives in PKGBUILD/SRCINFO and huge output files"
  files = [
    "repomix-output.xml"
  ]
  fingerprints = [
    "7fbc4c784949865f647ac654057c62039d10cf3d:glibc/.SRCINFO:generic-api-key:22",
    "7fbc4c784949865f647ac654057c62039d10cf3d:glibc/.SRCINFO:generic-api-key:23",
    "be5aa59f7bf905cf3cd8b5826bfd3387dd4ffb9e:llvm/.SRCINFO:generic-api-key:26",
    "be5aa59f7bf905cf3cd8b5826bfd3387dd4ffb9e:llvm/.SRCINFO:generic-api-key:28",
    "be5aa59f7bf905cf3cd8b5826bfd3387dd4ffb9e:llvm/.SRCINFO:generic-api-key:29",
    "c275f5d63b477afe588e270f8158cfa5df2ff267:mesa/.SRCINFO:generic-api-key:88",
    "c275f5d63b477afe588e270f8158cfa5df2ff267:mesa/.SRCINFO:generic-api-key:89",
    "c275f5d63b477afe588e270f8158cfa5df2ff267:mesa/.SRCINFO:generic-api-key:91",
    "c275f5d63b477afe588e270f8158cfa5df2ff267:mesa/.SRCINFO:generic-api-key:92",
    "c275f5d63b477afe588e270f8158cfa5df2ff267:mesa/.SRCINFO:generic-api-key:93",
    "cec00d348b0ddcf22458eb70427c3b49beae58e3:firefox/PKGBUILD:generic-api-key:100",
    "cec00d348b0ddcf22458eb70427c3b49beae58e3:firefox/PKGBUILD:gcp-api-key:95",
    "a65909c45750be512ee05874c42f9d21d6b7a423:chromium/PKGBUILD:generic-api-key:101",
    "a65909c45750be512ee05874c42f9d21d6b7a423:chromium/PKGBUILD:gcp-api-key:99",
    "a65909c45750be512ee05874c42f9d21d6b7a423:chromium/patches/helium/helium/core/ublock-setup-sources.patch:generic-api-key:160",
    "152307e85bae5f7a5b6efdc0d06005afc46c4fb8:firefox/ffox/PKGBUILD-vaapi:gcp-api-key:112",
    "152307e85bae5f7a5b6efdc0d06005afc46c4fb8:firefox/ffox/PKGBUILD-opensuse:gcp-api-key:152",
    "152307e85bae5f7a5b6efdc0d06005afc46c4fb8:firefox/ffox/PKGBUILD-opensuse:generic-api-key:154",
    "152307e85bae5f7a5b6efdc0d06005afc46c4fb8:firefox/ffox/PKGBUILD-opensuse:generic-api-key:161",
    "9e3663e1bc959d759aa6a3c520cf68d416df0cae:chromium/PKGBUILD:gcp-api-key:100",
    "9e3663e1bc959d759aa6a3c520cf68d416df0cae:zsh-pgo/.SRCINFO:generic-api-key:18",
    "9e3663e1bc959d759aa6a3c520cf68d416df0cae:zsh-pgo/.SRCINFO:generic-api-key:19",
    "9e3663e1bc959d759aa6a3c520cf68d416df0cae:zsh-pgo/.SRCINFO:generic-api-key:20",
    "02d7beeaf1a86f950fcbcfe6b94ef0614908a270:curl/patches/boringssl.patch:generic-api-key:1192",
    "1a11950d5a468a9333d9047f33765d5eaeb3bd7c:vscode/product.json:generic-api-key:1787",
    "a65909c45750be512ee05874c42f9d21d6b7a423:chromium/patches/patches-official/eyeo-133.0.6943.49-extension_api.patch:generic-api-key:4251",
    "a65909c45750be512ee05874c42f9d21d6b7a423:chromium/patches/patches-official/eyeo-133.0.6943.49-extension_api.patch:generic-api-key:5014",
    "a65909c45750be512ee05874c42f9d21d6b7a423:chromium/patches/patches-official/eyeo-133.0.6943.49-base.patch:generic-api-key:43540",
    "a65909c45750be512ee05874c42f9d21d6b7a423:chromium/patches/patches-official/eyeo-133.0.6943.49-base.patch:generic-api-key:50053",
    "1d8f63982505e8dfb487dda57e8289564966ed35:repomix-output.xml:generic-api-key:51144",
    "1d8f63982505e8dfb487dda57e8289564966ed35:repomix-output.xml:generic-api-key:52873",
    "1d8f63982505e8dfb487dda57e8289564966ed35:repomix-output.xml:generic-api-key:79822",
    "1d8f63982505e8dfb487dda57e8289564966ed35:repomix-output.xml:generic-api-key:82223",
    "1d8f63982505e8dfb487dda57e8289564966ed35:repomix-output.xml:generic-api-key:82224",
    "1d8f63982505e8dfb487dda57e8289564966ed35:repomix-output.xml:generic-api-key:86607",
    "1d8f63982505e8dfb487dda57e8289564966ed35:repomix-output.xml:generic-api-key:86609",
    "1d8f63982505e8dfb487dda57e8289564966ed35:repomix-output.xml:generic-api-key:86610",
    "1d8f63982505e8dfb487dda57e8289564966ed35:repomix-output.xml:gcp-api-key:51142",
    "1d8f63982505e8dfb487dda57e8289564966ed35:repomix-output.xml:gcp-api-key:79817"
  ]
