name: Update Packages

on:
  push:
    branches: [main]
    paths:
      - '**/PKGBUILD'
      - '**/**.install'
      - '**/**.sh'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq pacman namcap
      - name: Update packages.json
        run: |
          chmod +x vp-dev.py
          ./vp-dev.py update
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add packages.json
          git diff --cached --quiet || git commit -m "Update packages.json [automated]"
          git push
